### ISSUE TITLE
arm64: error with no error message

### ISSUE THREAD

**Issue by alexandru-elisei** [arichardson/freebsd#17]
While trying to do cross compiling on an Arch linux amd64 machine for arm64 I came across an error which stopped the compilation process, but for which I just couldn't find an error message in the logs. This is the complete compilation log: [arm64_no_error_message.log](https://github.com/arichardson/freebsd/files/3077638/arm64_no_error_message.log).

I had made the following changes to fix issue #16:
```
iff --git a/tools/build/cross-build/include/linux/unistd.h b/tools/build/cross-build/include/linux/unistd.h
index 8e939746712..010a9fa379c 100644
--- a/tools/build/cross-build/include/linux/unistd.h
+++ b/tools/build/cross-build/include/linux/unistd.h
@@ -42,11 +42,13 @@ strtofflags(char **stringp, u_long *setp, u_long *clrp) {
        return 0; /* success */
 }
 
+#if 0
 static inline int
 getentropy(void *buf, size_t buflen) {
 
        return syscall(__NR_getrandom, buf, buflen, 0);
 }
+#endif
 
 /* Used by elftoolchain: */
 extern char *program_invocation_name;
```
EDIT: Same clang/libc versions as in issue #16.

**Comment by arichardson** [comment]
Should be fixed now.

**Comment by alexandru-elisei** [comment]
Did you push a new commit? I did a git pull on crossbuild-aug2018 and I'm still seeing the issue.

**Comment by arichardson** [comment]
Ah sorry I didn't push.

**Comment by alexandru-elisei** [comment]
Still hitting the same problem.

**Comment by alexandru-elisei** [comment]
Log in #18.

**Comment by arichardson** [comment]
Can you build without -jN? That should hopefully give a more useful error message.

**Comment by alexandru-elisei** [comment]
Sure, I'll give it a go.

**Comment by alexandru-elisei** [comment]
No real error message without -jN: 
[arm64_no_jn.log](https://github.com/arichardson/freebsd/files/3086995/arm64_no_jn.log)

After looking at lib/libsysdecode/Makefile, I think that error code 1 is raised by the script lib/libsysdecode/mktables.

**Comment by arichardson** [comment]
I failed to reproduce this locally, could you change the `set -e` line in libsysdecode/mktables to `set -xe`? This should show which command is failing.

**Comment by alexandru-elisei** [comment]
Hi, thank you very much for your quick fixes, right now I'm on holiday, I'll test the fix next week and report here.

**Comment by alexandru-elisei** [comment]
I can confirm that it works now, thanks.
